name: CD
on:
  push:
    branches: [ master ]

jobs:
  deploy:    
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build

      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.SSH_USERNAME }}'
          server: '${{ secrets.SSH_HOST }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './build/*'
          remote_path: "/var/www/dev.gradskey.com/html/website"
          args: '-o ConnectTimeout=5'
  
